/*
 * This class file was automatically generated by ASN1bean v (http://www.beanit.com)
 */

package io.github.codicis.gsma.map.ts.code;

import com.beanit.asn1bean.ber.types.BerOctetString;

import java.io.Serial;


public class TeleserviceCode extends BerOctetString {

	@Serial
    private static final long serialVersionUID = 1L;

	public TeleserviceCode() {
	}

	public TeleserviceCode(byte[] value) {
		super(value);
	}

}
